services:
  frontend:
    build: frontend
    ports:
      - "80:4200"
    volumes:
      - ./frontend:/home/node/app
    environment:
      - COMMAND=run
  backend:
    build: backend
    ports:
      - "8019:3000"
    volumes:
      - ./backend:/home/node/app
    environment:
      - COMMAND=run
      - DATABASE_URL=mysql://szakdolgozat:DevelopmentPassword@database/szakdolgozat
    user: ${SZD_USERNAME:-node}
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=VerySecretPassword
      - MYSQL_DATABASE=szakdolgozat
      - MYSQL_USER=szakdolgozat
      - MYSQL_PASSWORD=DevelopmentPassword

networks:
  default:
    name: szakdolgozat
    driver: bridge
