services:
  frontend:
    build: frontend
    ports:
      - "80:4200"
    volumes:
      - ./frontend:/home/node/app
    environment:
      - NODE_ENV=development

networks:
  default:
    name: szakdolgozat
    driver: bridge
